require "bundler"
Bundler.require
require "minitest/autorun"
require_relative "../router"

def app; App end

Minitest::Apidoc.enable_plugin!

include Minitest::Apidoc::Methods

Minitest::Apidoc::Template.output_file = File.expand_path("../../doc/index.html", __FILE__)
Minitest::Apidoc::Template.blurb = <<-HTML
  <h1>minitest-apidoc example</h1>
  <p>This is an example of the documentation generated by <a href="https://github.com/lauri/minitest-apidoc">minitest-apidoc</a>.</p>
HTML
