$: << '.'
require 'bundler'
Bundler.require
require 'minitest/autorun'

require_relative '../router'

def app; App end

MiniTest::Reporters.use!([
  MiniTest::Reporters::DefaultReporter.new,
  MiniTest::Apidoc::Reporter.new
])

include MiniTest::Apidoc::Methods

MiniTest::Apidoc::Template.output_file = File.expand_path("../doc/index.html", File.dirname(__FILE__))
MiniTest::Apidoc::Template.blurb = <<-HTML
  <h1>minitest-apidoc example</h1>
  <p>This is an example of the documentation generated by <a href="http://github.com/kovalo/minitest-apidoc">minitest-apidoc</a>.</p>
HTML
